name: Deploy to Strato

on:
  push:
    branches:
      - main  # This triggers the script when you push to the 'main' branch

jobs:
  web-deploy:
    name: Sync Files
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4

      - name: ðŸ“‚ Sync files to Strato
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps      # Changed from sftp
          port: 21           # Changed from 22
          local-dir: ./
          server-dir: ./
